version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: danielz
      POSTGRES_PASSWORD: Daniel130102
      POSTGRES_DB: danielz
    ports:
      - "5432:5432" # Expose PostgreSQL port for web server to connect
    volumes:
      - ./data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
